services:
  - type: web
    name: expense-report-app
    env: python
    buildCommand: pip install -r expense-report-app/requirements.txt
    startCommand: python expense-report-app/app.py
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_KEY
